# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gb-blockchain.github.io" # the base hostname & protocol for your site

# Translations
BuyAndSell:
  en: Buy and Sell
  fr: Achats et ventes
BuyAndSellDesc:
  en: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
  fr: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
description:
  en: GC Blockchain Codefest will start April 17th, 2018.  The deadline for solution submissions is Monday, April 23rd at 9:00am EST.
  fr: Le festicode Blockchain GC débutera le 17 avril 2018. La date limite pour les soumissions de solutions est le lundi 23 avril à 9h00 HNE.
GoC:
  en: Government of Canada
  fr: Gouvernement du Canada
home:
  en: Home
  fr: Accueil
HowItWorks:
  en: How it works
  fr: Comment ça fonctionne
HowItWorksDesc:
  en: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque praesentium, nulla ab nobis architecto repellendus hic iure laboriosam.
  fr: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque praesentium, nulla ab nobis architecto repellendus hic iure laboriosam.
index:
  en: index.html
  fr: accueil.html
JoinConversation:
  en: Join the conversation
  fr: Rejoindre la conversation
language:
  en: English
  fr: Français
LanguageSelection:
  en: Language selection
  fr: Sélection de la langue
Locations:
  en: Locations
  fr: Emplacements
LocationsDesc:
  en: The primary codefest will occur in Ottawa for GC employees during the week of April 16th and confirmed satellite codefest locations will occur in Calgary, Montreal, Toronto, St. John’s, Seattle, Johannesburg, and Ghana.
  fr: Le Festicode principal se déroulera à Ottawa pour les employés du GC au cours de la semaine du 16 avril et des emplacements confirmés pour le code par satellite auront lieu à Calgary, Montréal, Toronto, St. John's, Seattle, Johannesburg et au Ghana.
Menu:
  en: Menu
  fr: Menu
MoreInformation:
  en: More information
  fr: Plus d'information
Rules:
  en: Rules
  fr: Règlements
RulesDesc:
  en: By entering the GC Blockchain Codefest, participants agree to abide by the rules and decisions of the organizers.
  fr: En participant au Festicode Blockchain GC, les participants acceptent de respecter les règles et les décisions des organisateurs.
SkipToMain:
  en: Skip to main content
  fr: Passer au contenu principal
SkipToAbout:
  en: Skip to "About this site"
  fr: Passer à « À propos de ce site »
TalentCloud:
  en: Talent Could
  fr: Nuage de talent
TalentCloudDesc:
  en: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
  fr: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
title:
  en: GC Blockchain Codefest
  fr: Festicode Blockchain GC
UseCasesThemes:
  en: Use Cases and Themes
  fr: Cas d'utilisation et thèmes
UseCasesThemesDesc:
  en: Teams will select one theme from a provided list of public sector use cases. Teams may contact TBS and propose an alternative public sector use case.
  fr: Les équipes sélectionneront un thème parmi une liste fournie de cas d'utilisation du secteur public. Les équipes peuvent contacter le SCT et proposer un autre cas d'utilisation du secteur public.

# Build settings
markdown: kramdown
include: ["_pages"]
